SeminarBuildingMap/Areas/Admin/Pages/AddRoomsToMap.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using SeminarBuildingMap.GenericClasses;
using SeminarBuildingMap.Models;

namespace SeminarBuildingMap
{
    public class AddRoomsToMapModel : PageModel
    {

        private readonly IOptions<ConnectionConfig> _connectionConfig;

        readonly RoomDataAccessLayer objRoom = new RoomDataAccessLayer();

        public IEnumerable<Room> Rooms { get; set; }

        public AddRoomsToMapModel(IOptions<ConnectionConfig> connectionConfig)
        {
            _connectionConfig = connectionConfig;
        }

        public void OnGet()
        {
            Rooms = objRoom.GetDardenRooms(_connectionConfig.Value.ConnStr);
        }

        public JsonResult OnGetAdd(String RoomNumber, String Coords)
        {
            objRoom.InsertDardenRoom(RoomNumber, Coords, _connectionConfig.Value.ConnStr);
            return new JsonResult("[success]");
        }
    }
}

SeminarBuildingMap/Areas/Admin/Pages/BuildingEditDisplay.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;

namespace SeminarBuildingMap.Areas.Admin.Pages
{
    //only admins can access this page
    [Authorize(Roles = "Admin")]
    public class BuildingEditDisplayModel : PageModel
    {
        readonly Models.BuildingDataAccessLayer ObjBuilding = new Models.BuildingDataAccessLayer(); //grabs an instance of BuildingDataAccess in order to communicate with SQL

        private readonly IOptions<GenericClasses.ConnectionConfig> _connectionConfig; 

        [BindProperty][StringLength(1)] //limit the string to a single character
        public string flNo { get; set; }

        [BindProperty][Display(Name ="Building Name")][StringLength(50)]
        public string bdName { get; set; }

        public IQueryable<Models.Floor> FloorData { get; set; } //holds the data for the floor datagrid
         
        public BuildingEditDisplayModel(IOptions<GenericClasses.ConnectionConfig> connectionConfig)
        {
            _connectionConfig = connectionConfig;
        }

        public void OnGet(string bdId) //sets the floor datagrid and the current building name textbox
        {
            FloorData = ObjBuilding.GetBuildingFloors(bdId, _connectionConfig.Value.ConnStr);
            bdName = ObjBuilding.GetBuildingName(bdId, _connectionConfig.Value.ConnStr);
        }

        public void OnPostUpdate(string bdId)
        {
            if (!String.IsNullOrEmpty(bdName)) //checks that a building name is supplied
            {
                ObjBuilding.UpdateBuilding(bdId, bdName, _connectionConfig.Value.ConnStr); //updates the building name
            } else
            {
                ModelState.AddModelError(string.Empty, "Building Name is required");
            }
            bdName = ObjBuilding.GetBuildingName(bdId, _connectionConfig.Value.ConnStr); //reload the data
            FloorData = ObjBuilding.GetBuildingFloors(bdId, _connectionConfig.Value.ConnStr);
        }

        public void OnPostAdd(string bdId)
        {
            if (!String.IsNullOrEmpty(flNo)) //floor must have a #
            {
                ObjBuilding.AddFloor(bdId, flNo, _connectionConfig.Value.ConnStr); //add new floor
            } else
            {
                ModelState.AddModelError(string.Empty, "Floor Number is required");
            }
            bdName = ObjBuilding.GetBuildingName(bdId, _connectionConfig.Value.ConnStr);
            FloorData = ObjBuilding.GetBuildingFloors(bdId, _connectionConfig.Value.ConnStr);
        }
    }
}

SeminarBuildingMap/Areas/Admin/Pages/BuildingEditSearch.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;

namespace SeminarBuildingMap.Areas.Admin.Pages
{
    [Authorize(Roles="Admin")]
    public class BuildingEditSearchModel : PageModel
    {
        readonly Models.BuildingDataAccessLayer ObjBuilding = new Models.BuildingDataAccessLayer();

        private readonly IOptions<GenericClasses.ConnectionConfig> _connectionConfig;

        [BindProperty][Required][Display(Name = "Building ID")][StringLength(20)]
        public string bdId { get; set; }

        public IQueryable<Models.Building> BuildingData { get; set; } 

        public BuildingEditSearchModel(IOptions<GenericClasses.ConnectionConfig> connectionConfig) 
        {
            _connectionConfig = connectionConfig;
        }

        public void OnGet()
        {
            BuildingData = ObjBuilding.GetAllBuildings(_connectionConfig.Value.ConnStr); //set building datagrid
        }

        public IActionResult OnPost()
        {
            if (!string.IsNullOrEmpty(bdId)) //add new building and redirect to it
            {
                ObjBuilding.AddBuilding(bdId, _connectionConfig.Value.ConnStr);
                return RedirectToPage("BuildingEditDisplay/", new {bdId = bdId });
            } else

            {
                return Page();
            }
        }

    }
}

SeminarBuildingMap/Areas/Admin/Pages/EditAvailability.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using SeminarBuildingMap.GenericClasses;

namespace SeminarBuildingMap.Areas.Admin.Pages
{
    public class EditAvailabilityModel : PageModel
    {
        private readonly IOptions<ConnectionConfig> _connectionConfig;

        readonly Models.RoomDataAccessLayer ObjRoom = new Models.RoomDataAccessLayer();

        readonly Models.RoomScheduleDataAccessLayer ObjSchedule = new Models.RoomScheduleDataAccessLayer();

        public string RoomName { get; set; }

        [BindProperty]
        public Models.RoomSchedule lclNewAvailability { get; set; }
        [BindProperty]
        public List<String> checkboxDays { get; set; } //holds the days selected for availability
        public IQueryable<Models.RoomSchedule> lclSchedule { get; set; }

        public EditAvailabilityModel(IOptions<ConnectionConfig> connectionConfig)
        {
            _connectionConfig = connectionConfig;
        }

        public void OnGet(int id)
        {
            lclSchedule = ObjSchedule.GetRoomAvailability(id, _connectionConfig.Value.ConnStr); //load the schedule with availabilties for the room
            RoomName = ObjRoom.GetRoomInfo(id, _connectionConfig.Value.ConnStr).rmName;
        }

        public void OnPostSave(int id)
        {
            lclNewAvailability.rmId = id;
            if (ModelState.IsValid && ObjRoom.UserCanEditRoom(User.Identity.Name, id, _connectionConfig.Value.ConnStr)) //checks to make sure user has permissions over this room
            {
                if (lclNewAvailability.avId == 0) //if availability # is 0, then its a new record
                {
                    var validDays = new List<String> { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }; //ensures added day is valid 
                    if(checkboxDays.Count == 0)
                    {
                        ModelState.AddModelError(String.Empty, "Atleast one day must be selected");
                    }
                    foreach (string day in checkboxDays) //insert each each availability
                    {
                        if (validDays.Contains(day))
                        {
                            lclNewAvailability.avDay = day;
                            ObjSchedule.InsertRoomAvailability(lclNewAvailability, _connectionConfig.Value.ConnStr);
                            ModelState.Clear();
                        }
                    }
                }
                else //edits the selected availability
                {
                    ObjSchedule.EditRoomAvailability(lclNewAvailability, _connectionConfig.Value.ConnStr);
                    ModelState.Clear();
                }
            } else
            {
                ModelState.AddModelError(String.Empty, "Error: Invalid Request");
            }
            lclSchedule = ObjSchedule.GetRoomAvailability(id, _connectionConfig.Value.ConnStr);
            lclNewAvailability = new Models.RoomSchedule();
            RoomName = ObjRoom.GetRoomInfo(id, _connectionConfig.Value.ConnStr).rmName;
        }

        public void OnPostDelete(int id)
        {
            if(ModelState.IsValid && ObjRoom.UserCanEditRoom(User.Identity.Name, id, _connectionConfig.Value.ConnStr))
            {
                if (lclNewAvailability.avId != 0) //can't delete a record that isn't in the database
                {
                    ObjSchedule.DeleteRoomAvailability(lclNewAvailability.avId, _connectionConfig.Value.ConnStr);
                    ModelState.Clear();
                } else
                {
                    ModelState.AddModelError(string.Empty, "An availability record must be selected to delete");
                }
            } else
            {
                ModelState.AddModelError(string.Empty, "Error: Invalid Request"); //shouldn't ever be reached, but better safe than sorry
            }
            lclSchedule = ObjSchedule.GetRoomAvailability(id, _connectionConfig.Value.ConnStr);
            lclNewAvailability = new Models.RoomSchedule();
            RoomName = ObjRoom.GetRoomInfo(id, _connectionConfig.Value.ConnStr).rmName;
        }
    }

}

SeminarBuildingMap/Areas/Admin/Pages/EditEvent.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using SeminarBuildingMap.GenericClasses;

namespace SeminarBuildingMap.Areas.Admin.Pages
{
    //this is pretty much identical to availability, so just check that code to see how this works
    public class EditEventModel : PageModel
    {
        private readonly IOptions<ConnectionConfig> _connectionConfig;

        readonly Models.RoomDataAccessLayer ObjRoom = new Models.RoomDataAccessLayer();

        readonly Models.RoomScheduleDataAccessLayer ObjSchedule = new Models.RoomScheduleDataAccessLayer();

        public string RoomName { get; set; }

        [BindProperty]
        public Models.RoomSchedule lclNewEvent { get; set; }
        public IQueryable<Models.RoomSchedule> lclSchedule { get; set; }

        public EditEventModel(IOptions<ConnectionConfig> connectionConfig)
        {
            _connectionConfig = connectionConfig;
        }
        public void OnGet(int id)
        {
            lclSchedule = ObjSchedule.GetRoomEvents(id, _connectionConfig.Value.ConnStr);
            RoomName = ObjRoom.GetRoomInfo(id, _connectionConfig.Value.ConnStr).rmName;
        }

        public void OnPostSave(int id)
        {
            lclNewEvent.rmId = id;
            if (ModelState.IsValid && ObjRoom.UserCanEditRoom(User.Identity.Name, id, _connectionConfig.Value.ConnStr))
            {
                if (lclNewEvent.avId == 0)
                {
                    ObjSchedule.InsertRoomEvent(lclNewEvent, _connectionConfig.Value.ConnStr);
                }
                else
                {
                    ObjSchedule.EditRoomEvent(lclNewEvent, _connectionConfig.Value.ConnStr);
                }
            } else
            {
                ModelState.AddModelError(string.Empty, "Error: Invalid Request");
            }
            lclSchedule = ObjSchedule.GetRoomEvents(id, _connectionConfig.Value.ConnStr);
            lclNewEvent = new Models.RoomSchedule();
            RoomName = ObjRoom.GetRoomInfo(id, _connectionConfig.Value.ConnStr).rmName;
        }

        public void OnPostDelete(int id)
        {
            if (ModelState.IsValid && ObjRoom.UserCanEditRoom(User.Identity.Name, id, _connectionConfig.Value.ConnStr))
            {
                if (lclNewEvent.avId != 0)
                {
                    ObjSchedule.DeleteRoomEvent(lclNewEvent.avId, _connectionConfig.Value.ConnStr);
                }
            } else
            {
                ModelState.AddModelError(string.Empty, "Error: Invalid Request");
            }
            lclSchedule = ObjSchedule.GetRoomEvents(id, _connectionConfig.Value.ConnStr);
            lclNewEvent = new Models.RoomSchedule();
            RoomName = ObjRoom.GetRoomInfo(id, _connectionConfig.Value.ConnStr).rmName;
        }
    }
}

SeminarBuildingMap/Areas/Admin/Pages/FloorEditDisplay.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;

namespace SeminarBuildingMap.Areas.Admin.Pages
{
    public class FloorEditDisplayModel : PageModel
    {

        readonly Models.BuildingDataAccessLayer ObjBuilding = new Models.BuildingDataAccessLayer();

        private readonly IOptions<GenericClasses.ConnectionConfig> _connectionConfig;

        private IWebHostEnvironment _environment; //used to find paths to save file

        [BindProperty][StringLength(50)]
        public string flName { get; set; }

        [BindProperty]
        public IFormFile Upload { get; set; } //holds uploaded file

        public bool isFloorPlan { get; set; } //stores if svg is saved already

        public FloorEditDisplayModel(IOptions<GenericClasses.ConnectionConfig> connectionConfig, IWebHostEnvironment environment)
        {
            _connectionConfig = connectionConfig;
            _environment = environment;
        }
        public void OnGet(string bdId, string flNo)
        {
            flName = ObjBuilding.GetFloorName(bdId, flNo, _connectionConfig.Value.ConnStr); //gets the floorname from its id
            isFloorPlan = System.IO.File.Exists(Path.Combine(_environment.ContentRootPath, "wwwroot/images", bdId + flNo + ".svg")); //checks to see if file is already saved on webserver
        }

        public void OnPostUpdate(string bdId, string flNo)
        {
            if (!String.IsNullOrEmpty(flName))
            {
                ObjBuilding.UpdateFloorName(bdId, flNo, flName, _connectionConfig.Value.ConnStr);
            } 
            else
            {
                ModelState.AddModelError(string.Empty, "Floor Name is Required");
            }
            flName = ObjBuilding.GetFloorName(bdId, flNo, _connectionConfig.Value.ConnStr);
            isFloorPlan = System.IO.File.Exists(Path.Combine(_environment.ContentRootPath, "wwwroot/images", bdId + flNo + ".svg"));
        }

        public void OnPostUploadAsync(string bdId, string flNo) //handles uploading file
        {
            if (!(Upload == null))
            {
                string[] extension = Upload.FileName.Split(".");
                if (extension[extension.Length - 1].ToLower() == "svg") //ensurs the uploaded file atleast is an .svg file
                {
                    string fileName = bdId + flNo + ".svg"; //ignore what the files name is, instead change it to  what the system requires
                    var file = Path.Combine(_environment.ContentRootPath, "wwwroot/images", fileName); //create the path to save it on
                    using (var fileStream = new FileStream(file, FileMode.Create)) 
                    {
                        Upload.CopyTo(fileStream); //do the actual write
                    }
                } else
                {
                    ModelState.AddModelError(string.Empty, "Floorplan must be a .svg file");
                }
            } else
            {
                ModelState.AddModelError(string.Empty, "Floorplan file is required");
            }
            flName = ObjBuilding.GetFloorName(bdId, flNo, _connectionConfig.Value.ConnStr);
            isFloorPlan = System.IO.File.Exists(Path.Combine(_environment.ContentRootPath, "wwwroot/images", bdId + flNo + ".svg"));
        }
    }
}

SeminarBuildingMap/Areas/Admin/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SeminarBuildingMap.Areas.Admin.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SeminarBuildingMap/Areas/Admin/Pages/RegisterConfirm.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SeminarBuildingMap.Areas.Admin.Pages
{
    [Authorize(Roles = "Admin,Manager")]
    public class RegisterConfirmModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SeminarBuildingMap/Areas/Identity/Pages/Account/RegisterConfirm.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SeminarBuildingMap.Areas.Identity.Pages.Account
{
    public class RegisterConfirmModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SeminarBuildingMap/Areas/Admin/Pages/BuildingEditDisplay.cshtml
@page "{bdId}"
@model SeminarBuildingMap.Areas.Admin.Pages.BuildingEditDisplayModel
@{
    ViewData["Title"] = "Edit Building";
}
<div asp-validation-summary="All" class="text-danger"></div>
<form method="post">
    <h2 class="font-weight-bold text-dark border-bottom">Edit Building Information</h2>
    <div class="form-group">
        <label class="text-dark font-weight-bold">Building ID</label>
        <input class="form-control shadow" value="@RouteData.Values["bdId"]" readonly />
    </div>
    <div class="form-group">
        <label class="text-dark font-weight-bold">Building Name</label>
        <input class="form-control shadow" asp-for="bdName" maxlength="50" />
    </div>
    <button type="submit" class="btn btn-dark text-light font-weight-bolder shadow" asp-page-handler="update">Update Building Name</button>
    <br /><br />

    <h2 class="font-weight-bold text-dark border-bottom">Edit Building Floors</h2>

    @(Html
        .Grid(Model.FloorData)
        .Build(columns =>
        {
            columns.Add(model => model.flNo).Titled("Floor Number");
            columns.Add(model => model.flName).Titled("Floor Name");
        })
        .Empty("No Floors Found For This Building")
        .Sortable()
        .Pageable()
        .Filterable()
    )
    <br />

    <div class="form-group">
        <label class="text-dark font-weight-bold">Floor Number</label>
        <input class="form-control shadow" asp-for="flNo" maxlength="1" />
    </div>
    <button type="submit" class="btn btn-dark text-light font-weight-bolder shadow" asp-page-handler="add">Add New Floor</button>
</form>


@section Scripts
{
    <script src="~/js/mvc-grid/mvc-grid.js"></script>
    <script>
        [].forEach.call(document.getElementsByClassName('mvc-grid'), function (element) {
            new MvcGrid(element);
        });
    </script>
    <script>
        document.addEventListener('rowclick', function (e) {
            window.location.href = "../FloorEditDisplay/" + "@RouteData.Values["bdId"]" + "/"  + e.detail.data['fl-no'];
        });
    </script>

    <partial name="_ValidationScriptsPartial" />

}

SeminarBuildingMap/Areas/Admin/Pages/EditOwners.cshtml
@page "{id}"
@model SeminarBuildingMap.Areas.Admin.Pages.EditOwnersModel
@{
    ViewData["Title"] = "Edit Room Users";
}
<a asp-page="OwnedRoomSearch/" class="btn btn-dark text-light font-weight-bolder pull-right shadow">Return to search</a>
<br /><br />

<h1 class="text-dark font-weight-bolder">Edit @Model.RoomName</h1>
<div asp-validation-summary="All" class="text-danger"></div>
<ul class="nav nav-tabs" role="tablist">
    <li class="nav-item"><a class="nav-link font-weight-bolder" role="tab" aria-controls="home" aria-selected="false" asp-page="OwnedRoomDisplay/" asp-route-id="@RouteData.Values["id"]">View/Edit Room</a></li>
    <li class="nav-item"><a class="nav-link font-weight-bolder" role="tab" aria-controls="home" aria-selected="false" asp-page="EditAvailability/" asp-route-id="@RouteData.Values["id"]">View/Edit Availability</a></li>
    <li class="nav-item"><a class="nav-link font-weight-bolder" role="tab" aria-controls="home" aria-selected="false" asp-page="EditEvent/" asp-route-id="@RouteData.Values["id"]">View/Edit Events</a></li>
    <li class="nav-item shadow"><a class="nav-link active font-weight-bolder" role="tab" aria-controls="home" aria-selected="true" asp-page="EditOwners/">View/Edit Assigned Persons</a></li>
</ul>
<br />
<div class="tab-content">
    <div class="tab-pane fade show active">
        <form method="post">
            <h2 class="font-weight-normal text-dark border-bottom">Add User</h2>
            @(Html
                .Grid(Model.allUsers)
                .Build(columns =>
                {
                    columns.Add(model => model.Email).Titled("Email");
                    columns.Add(model => model.FirstName).Titled("First Name");
                    columns.Add(Model => Model.LastName).Titled("Last Name");

                    })
                .Empty("No Available Users")
                .Sortable()
                .Pageable()
                .Named("allUsers")
                .Filterable()
            )

            <div class="form-group">
                <label class="text-dark font-weight-bold" style="padding-top:15px">Add</label>
                <input class="form-control shadow" id="addusers" asp-for="UsersToAdd" />
            </div>

            <button type="submit" id="submit" class="btn btn-dark text-light font-weight-bolder shadow" asp-page-handler="save">Add</button>
            <br /><br />
            <h2 class="font-weight-normal text-dark border-bottom">Delete User</h2>
            @(Html
                .Grid(Model.ownedUsers)
                .Build(columns =>
                {
                    columns.Add(model => model.UserName).Titled("Email");
                    columns.Add(model => model.FirstName).Titled("First Name");
                    columns.Add(Model => Model.LastName).Titled("Last Name");

                    })
                .Empty("No Available Users")
                .Sortable()
                .Pageable()
                .Named("ownedUsers")
                .Filterable()
            )

            <div class="form-group">
                <label class="text-dark font-weight-bold" style="padding-top:15px">Delete</label>
                <input class="form-control shadow" id="deleteusers" asp-for="UsersToDelete" />
            </div>

            <button type="submit" id="delete" class="btn btn-danger text-light font-weight-bolder shadow" asp-page-handler="delete">Delete Selected</button>

        </form>
    </div>
</div>
@section Scripts
{
    <script src="~/js/mvc-grid/mvc-grid.js"></script>
    <script>
        [].forEach.call(document.getElementsByClassName('mvc-grid'), function (element) {
            new MvcGrid(element);
        });
    </script>

    <script>
        document.addEventListener('rowclick', function (e) {
            if (e.detail.grid["name"] == "owned-users") {
                document.getElementById("deleteusers").value += (e.detail.data["user-name"] + ", ");
            }
            if (e.detail.grid["name"] == "all-users") {
                document.getElementById("addusers").value += (e.detail.data["email"] + ", ");
            }
        });
    </script>

    <partial name="_ValidationScriptsPartial" />

}

SeminarBuildingMap/Areas/Admin/Pages/FloorEditRooms.cshtml
@page "{bdId}/{flNo}"
@model SeminarBuildingMap.FloorEditDisplayModel
@{
    ViewData["Title"] = "Edit Floor - Rooms";
    //allows admin to add/remove rooms or change building info(name)
}
@section Mapping{
    <link rel="stylesheet" href="~/css/leaflet.css" />
    <script src="~/js/leaflet.js"></script>

    <style>
        #mapid {
            height: 750px;
        }
    </style>

    <input id="building" value="@RouteData.Values["bdId"]" type="hidden" />
    <input id="floor" value="@RouteData.Values["flNo"]" type="hidden" />

}

<script>
    function clearText() {
        document.getElementById("coords").textContent = "";
    }
</script>
<div asp-validation-summary="All" class="text-danger"></div>
<ul class="nav nav-tabs" role="tablist">
    <li class="nav-item active"><a class="nav-link active font-weight-bolder" data-toggle="tab" aria-controls="home" aria-selected="true" href="#add">Add Room</a></li>
    <li class="nav-item"><a class="nav-link font-weight-bolder" data-toggle="tab" aria-controls="home" aria-selected="false" href="#edit">Edit Room</a></li>
</ul>
<form method="post">
    <div class="tab-content">
        <div class="tab-pane fade in active show p-2" id="add">
            <input id="coords" type="hidden" asp-for="coords" />
            <div class="form-group">
                <label class="text-dark font-weight-bold">Room Number</label>
                <input class="form-control shadow" id="newNumber" asp-for="newRmNo" maxlength="10" />
            </div>
            <button type="submit" id="add" class="btn btn-dark text-light font-weight-bolder shadow" asp-page-handler="add" asp-route-bdId="@RouteData.Values["bdId"]" asp-route-flNo="@RouteData.Values["flNo"]">Add Room</button>
            <button class="btn btn-secondary text-light font-weight-bolder shadow" onclick="clearMarkers()">Restart Room</button>
            <br /><br />
            <p class="text-dark font-weight-bold">Start with the top left point of a room, and go counter clockwise for the rest of the points to add a room. Exactly 4 points must be added.</p>
        </div>
        <div class="tab-pane fade p-2" id="edit">
            <div class="form-group">
                <label class="text-dark font-weight-bold">Selected Room ID</label>
                <input class="form-control shadow" asp-for="rmId" id="idLabel" readonly />
            </div>
            <div class="form-group">
                <label class="text-dark font-weight-bold">Room Number</label>
                <input class="form-control shadow" asp-for="rmNo" id="numberLabel" maxlength="10" />
            </div>
            <button type="submit" id="update" class="btn btn-dark text-light font-weight-bolder shadow" asp-page-handler="update" asp-route-bdId="@RouteData.Values["bdId"]" asp-route-flNo="@RouteData.Values["flNo"]">Update Room</button>
            <button type="submit" id="delete" class="btn btn-danger text-light font-weight-bolder shadow" asp-page-handler="delete" asp-route-bdId="@RouteData.Values["bdId"]" asp-route-flNo="@RouteData.Values["flNo"]" onclick="return confirm('Are you sure you want to delete this room?')">Delete Room</button>
        </div>
    </div>
</form>


<div id="mapid"></div>
<script src="~/js/AddRoomsMap.js"></script>

<script>
    var rooms = [
    @for(int i = 0; i < Model.Rooms.Count(); i++)
    {

        SeminarBuildingMap.Models.Room room = Model.Rooms.ElementAt(i);
        <text>
        {
            "type": "Feature",
            "properties": { "id": "@room.rmId", "number": "@room.rmNo"},
            "geometry": {
                "type": "Polygon",
                "coordinates": [[[@room.rmTopLeftPoint],[@room.rmBottomLeftPoint],[@room.rmBottomRightPoint],[@room.rmTopRightPoint]]]
                }
        }
        </text>
        @if(i != Model.Rooms.Count() - 1)
        {
            <text>,</text>
        }
    }
        ];

    function style(feature) {
        return {
            fillColor: "Blue"
        };
    }

var geoJson = L.geoJSON(rooms, { style: style, onEachFeature: onEachFeature }).addTo(map);
</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}